NetworkExpansion: 1
TimeDomainReductionFolder: "TDR_Results"
ModelingToGenerateAlternativeIterations: 3
ParameterScale: 1
EnergyShareRequirement: 0
PrintModel: 1
OperationWrapping: 1
TimeDomainReduction: 1
Trans_Loss_Segments: 1
CapacityReserveMargin: 1
ModelingtoGenerateAlternativeSlack: 0.1
Solver: "Gurobi"
MethodofMorris: 0
Reserves: 0
StorageLosses: 1
OverwriteResults: 1
UCommit: 2
ModelingToGenerateAlternatives: 0
MinCapReq: 0
MaxCapReq: 0
CO2Cap: 1
WriteShadowPrices: 1
EnableJuMPStringNames: 1
VreStor: 1
