NetworkExpansion: 1
TimeDomainReductionFolder: "TDR_Results"
ModelingToGenerateAlternativeIterations: 3
ParameterScale: 0
EnergyShareRequirement: 0
PrintModel: 0
TimeDomainReduction: 1
Trans_Loss_Segments: 1
CapacityReserveMargin: 1
ModelingtoGenerateAlternativeSlack: 0.1
Solver: "Gurobi"
MethodofMorris: 0
Reserves: 0
StorageLosses: 1
OverwriteResults: 1
UCommit: 2
ModelingToGenerateAlternatives: 0
MaxCapReq: 1
MinCapReq: 1
MinCapReqEqual: 1
CO2Cap: 1
WriteShadowPrices: 1
OperationWrapping: 1
VreStor: 0